spring.application.name=API
# datasource
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:sistemaEcommerce
spring.datasource.username=maymsan
spring.datasource.password=a27V34H9
# jpa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
debug=true

# h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SpringDoc
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/